spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MALL_MYSQL_USER}
    password: ${MALL_MYSQL_PASSWORD}
